language: ruby
cache: bundler
sudo: false

rvm:
  - 2

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
